// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package openapi

// English defines model for english.
type English struct {
	Example *string `json:"example,omitempty"`
	Word    *string `json:"word,omitempty"`
}

// EnglishSummary defines model for englishSummary.
type EnglishSummary struct {
	Words *[]English `json:"words,omitempty"`
}

// Kanji defines model for kanji.
type Kanji struct {
	Character string  `json:"character"`
	Hun       *string `json:"hun,omitempty"`
	Yomi      *string `json:"yomi,omitempty"`
}

// KanjiSummary defines model for kanjiSummary.
type KanjiSummary struct {
	Description *string `json:"description,omitempty"`
	Kanji       Kanji   `json:"kanji"`
	Usage       *Usage  `json:"usage,omitempty"`
}

// Usage defines model for usage.
type Usage struct {
	Contents *[]string `json:"contents,omitempty"`
	Header   string    `json:"header"`
}

// PostEnglishMarkdownJSONRequestBody defines body for PostEnglishMarkdown for application/json ContentType.
type PostEnglishMarkdownJSONRequestBody = EnglishSummary

// PostKanjiMarkdownJSONRequestBody defines body for PostKanjiMarkdown for application/json ContentType.
type PostKanjiMarkdownJSONRequestBody = KanjiSummary
